/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AllianceDtVo,
  ChangePasswordAfterFindPasswordBody,
  CommitteeVo,
  FacultyListResponse,
  GetPcoInfoForFirstBody,
  GetSettingByTypeBody,
  GetTermsVersionByTypeBody,
  GetTermsVersionMaxBody,
  PasswordFindRequest,
  PcoBaseInfoVo,
  PcoBoardMemberVo,
  PcoLocationVo,
  PcoMenuTopVo,
  ResponseMessageVo,
  SendEmailVerificationCodeForRegister200,
  SessionCategoryVo,
  SettingVo,
  SponsorVo,
  TermsVo,
} from '../../model';

/**
 * 해당 학회 최신 버전의 약관 정보 가져오기
 * @summary public : getSettingByType
 */
export const getTermsVersionMax = (
  getTermsVersionMaxBody: GetTermsVersionMaxBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TermsVo>> => {
  return axios.post(`/api/public/pco/terms`, getTermsVersionMaxBody, options);
};

export const getGetTermsVersionMaxMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getTermsVersionMax>>,
    TError,
    { data: GetTermsVersionMaxBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getTermsVersionMax>>,
  TError,
  { data: GetTermsVersionMaxBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getTermsVersionMax>>,
    { data: GetTermsVersionMaxBody }
  > = (props) => {
    const { data } = props ?? {};

    return getTermsVersionMax(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetTermsVersionMaxMutationResult = NonNullable<
  Awaited<ReturnType<typeof getTermsVersionMax>>
>;
export type GetTermsVersionMaxMutationBody = GetTermsVersionMaxBody;
export type GetTermsVersionMaxMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getSettingByType
 */
export const useGetTermsVersionMax = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getTermsVersionMax>>,
    TError,
    { data: GetTermsVersionMaxBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetTermsVersionMaxMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 해당 학회 버전별 약관 정보 가져오기
 * @summary public : getSettingByType
 */
export const getTermsVersionByType = (
  getTermsVersionByTypeBody: GetTermsVersionByTypeBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TermsVo>> => {
  return axios.post(
    `/api/public/pco/terms-version`,
    getTermsVersionByTypeBody,
    options
  );
};

export const getGetTermsVersionByTypeMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getTermsVersionByType>>,
    TError,
    { data: GetTermsVersionByTypeBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getTermsVersionByType>>,
  TError,
  { data: GetTermsVersionByTypeBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getTermsVersionByType>>,
    { data: GetTermsVersionByTypeBody }
  > = (props) => {
    const { data } = props ?? {};

    return getTermsVersionByType(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetTermsVersionByTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof getTermsVersionByType>>
>;
export type GetTermsVersionByTypeMutationBody = GetTermsVersionByTypeBody;
export type GetTermsVersionByTypeMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getSettingByType
 */
export const useGetTermsVersionByType = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getTermsVersionByType>>,
    TError,
    { data: GetTermsVersionByTypeBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetTermsVersionByTypeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 해당 학회 타입별 세팅 정보 가져오기
 * @summary public : getSettingByType
 */
export const getSettingByType = (
  getSettingByTypeBody: GetSettingByTypeBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SettingVo>> => {
  return axios.post(`/api/public/pco/setting`, getSettingByTypeBody, options);
};

export const getGetSettingByTypeMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getSettingByType>>,
    TError,
    { data: GetSettingByTypeBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getSettingByType>>,
  TError,
  { data: GetSettingByTypeBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getSettingByType>>,
    { data: GetSettingByTypeBody }
  > = (props) => {
    const { data } = props ?? {};

    return getSettingByType(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetSettingByTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof getSettingByType>>
>;
export type GetSettingByTypeMutationBody = GetSettingByTypeBody;
export type GetSettingByTypeMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getSettingByType
 */
export const useGetSettingByType = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getSettingByType>>,
    TError,
    { data: GetSettingByTypeBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetSettingByTypeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 학회 클라이언트 첫 페이지 로딩시 해당하는 학회의 정보 가져오기
 * @summary public : getEnterprisePcoList
 */
export const getPcoInfoForFirst = (
  getPcoInfoForFirstBody: GetPcoInfoForFirstBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoBaseInfoVo>> => {
  return axios.post(
    `/api/public/pco/pco-info`,
    getPcoInfoForFirstBody,
    options
  );
};

export const getGetPcoInfoForFirstMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPcoInfoForFirst>>,
    TError,
    { data: GetPcoInfoForFirstBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getPcoInfoForFirst>>,
  TError,
  { data: GetPcoInfoForFirstBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getPcoInfoForFirst>>,
    { data: GetPcoInfoForFirstBody }
  > = (props) => {
    const { data } = props ?? {};

    return getPcoInfoForFirst(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetPcoInfoForFirstMutationResult = NonNullable<
  Awaited<ReturnType<typeof getPcoInfoForFirst>>
>;
export type GetPcoInfoForFirstMutationBody = GetPcoInfoForFirstBody;
export type GetPcoInfoForFirstMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getEnterprisePcoList
 */
export const useGetPcoInfoForFirst = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPcoInfoForFirst>>,
    TError,
    { data: GetPcoInfoForFirstBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetPcoInfoForFirstMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 비밀번호 찾기를 위해 이메일 혹은 메시지를 통해 인증번호를 보내기
 * @summary public : requestVerificationCodeForFindPassword
 */
export const requestVerificationCodeForFindPassword = (
  passwordFindRequest: PasswordFindRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SessionCategoryVo>> => {
  return axios.post(
    `/api/public/pco/find-password/verification-code`,
    passwordFindRequest,
    options
  );
};

export const getRequestVerificationCodeForFindPasswordMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestVerificationCodeForFindPassword>>,
    TError,
    { data: PasswordFindRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestVerificationCodeForFindPassword>>,
  TError,
  { data: PasswordFindRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestVerificationCodeForFindPassword>>,
    { data: PasswordFindRequest }
  > = (props) => {
    const { data } = props ?? {};

    return requestVerificationCodeForFindPassword(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestVerificationCodeForFindPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestVerificationCodeForFindPassword>>
>;
export type RequestVerificationCodeForFindPasswordMutationBody =
  PasswordFindRequest;
export type RequestVerificationCodeForFindPasswordMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary public : requestVerificationCodeForFindPassword
 */
export const useRequestVerificationCodeForFindPassword = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestVerificationCodeForFindPassword>>,
    TError,
    { data: PasswordFindRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getRequestVerificationCodeForFindPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 비밀번호 찾기 후 비밀번호 변경
 * @summary public : pcoClientChangePassword
 */
export const changePasswordAfterFindPassword = (
  changePasswordAfterFindPasswordBody: ChangePasswordAfterFindPasswordBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/public/pco/find-password/password-change`,
    changePasswordAfterFindPasswordBody,
    options
  );
};

export const getChangePasswordAfterFindPasswordMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePasswordAfterFindPassword>>,
    TError,
    { data: ChangePasswordAfterFindPasswordBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changePasswordAfterFindPassword>>,
  TError,
  { data: ChangePasswordAfterFindPasswordBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changePasswordAfterFindPassword>>,
    { data: ChangePasswordAfterFindPasswordBody }
  > = (props) => {
    const { data } = props ?? {};

    return changePasswordAfterFindPassword(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangePasswordAfterFindPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof changePasswordAfterFindPassword>>
>;
export type ChangePasswordAfterFindPasswordMutationBody =
  ChangePasswordAfterFindPasswordBody;
export type ChangePasswordAfterFindPasswordMutationError = AxiosError<unknown>;

/**
 * @summary public : pcoClientChangePassword
 */
export const useChangePasswordAfterFindPassword = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePasswordAfterFindPassword>>,
    TError,
    { data: ChangePasswordAfterFindPasswordBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getChangePasswordAfterFindPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
export const sendEmailVerificationCodeForRegister = (
  serviceType: string,
  confStringIdx: string,
  email: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SendEmailVerificationCodeForRegister200>> => {
  return axios.get(
    `/api/public/${serviceType}/${confStringIdx}/user/send_email/${email}/verification-code`,
    options
  );
};

export const getSendEmailVerificationCodeForRegisterQueryKey = (
  serviceType: string,
  confStringIdx: string,
  email: string
) => {
  return [
    `/api/public/${serviceType}/${confStringIdx}/user/send_email/${email}/verification-code`,
  ] as const;
};

export const getSendEmailVerificationCodeForRegisterQueryOptions = <
  TData = Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>,
  TError = AxiosError<unknown>,
>(
  serviceType: string,
  confStringIdx: string,
  email: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSendEmailVerificationCodeForRegisterQueryKey(
      serviceType,
      confStringIdx,
      email
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>
  > = ({ signal }) =>
    sendEmailVerificationCodeForRegister(serviceType, confStringIdx, email, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(serviceType && confStringIdx && email),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SendEmailVerificationCodeForRegisterQueryResult = NonNullable<
  Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>
>;
export type SendEmailVerificationCodeForRegisterQueryError =
  AxiosError<unknown>;

export const useSendEmailVerificationCodeForRegister = <
  TData = Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>,
  TError = AxiosError<unknown>,
>(
  serviceType: string,
  confStringIdx: string,
  email: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sendEmailVerificationCodeForRegister>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSendEmailVerificationCodeForRegisterQueryOptions(
    serviceType,
    confStringIdx,
    email,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회 메뉴 가져오기
 * @summary public : getPcoMenu
 */
export const getMenu = (
  conferenceIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoMenuTopVo>> => {
  return axios.get(`/api/public/pco/${conferenceIdx}/menu`, options);
};

export const getGetMenuQueryKey = (conferenceIdx: number) => {
  return [`/api/public/pco/${conferenceIdx}/menu`] as const;
};

export const getGetMenuQueryOptions = <
  TData = Awaited<ReturnType<typeof getMenu>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMenuQueryKey(conferenceIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenu>>> = ({
    signal,
  }) => getMenu(conferenceIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!conferenceIdx,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetMenuQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMenu>>
>;
export type GetMenuQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getPcoMenu
 */
export const useGetMenu = <
  TData = Awaited<ReturnType<typeof getMenu>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMenuQueryOptions(conferenceIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 푸터 바로가기 아이콘 리스트 정보 가져오기
 * @summary public : getFooterShortcutIconsInEachMainPage
 */
export const getFooterShortcutIconsInEachMainPage = (
  conferenceIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AllianceDtVo>> => {
  return axios.get(
    `/api/public/pco/${conferenceIdx}/footer-shortcut-icons`,
    options
  );
};

export const getGetFooterShortcutIconsInEachMainPageQueryKey = (
  conferenceIdx: number
) => {
  return [`/api/public/pco/${conferenceIdx}/footer-shortcut-icons`] as const;
};

export const getGetFooterShortcutIconsInEachMainPageQueryOptions = <
  TData = Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFooterShortcutIconsInEachMainPageQueryKey(conferenceIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>
  > = ({ signal }) =>
    getFooterShortcutIconsInEachMainPage(conferenceIdx, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!conferenceIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFooterShortcutIconsInEachMainPageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>
>;
export type GetFooterShortcutIconsInEachMainPageQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary public : getFooterShortcutIconsInEachMainPage
 */
export const useGetFooterShortcutIconsInEachMainPage = <
  TData = Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFooterShortcutIconsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetFooterShortcutIconsInEachMainPageQueryOptions(
    conferenceIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 사무국 정보 가져오기
 * @summary public : getCommittee
 */
export const getCommittee = (
  conferenceIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<CommitteeVo>> => {
  return axios.get(`/api/public/pco/${conferenceIdx}/committee`, options);
};

export const getGetCommitteeQueryKey = (conferenceIdx: number) => {
  return [`/api/public/pco/${conferenceIdx}/committee`] as const;
};

export const getGetCommitteeQueryOptions = <
  TData = Awaited<ReturnType<typeof getCommittee>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommittee>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCommitteeQueryKey(conferenceIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommittee>>> = ({
    signal,
  }) => getCommittee(conferenceIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!conferenceIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCommittee>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCommitteeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCommittee>>
>;
export type GetCommitteeQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getCommittee
 */
export const useGetCommittee = <
  TData = Awaited<ReturnType<typeof getCommittee>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  conferenceIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommittee>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCommitteeQueryOptions(conferenceIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 바로가기 버튼 정보 가져오기
 * @summary public : getShortcutsInEachMainPage
 */
export const getShortcutsInEachMainPage = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AllianceDtVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/shortcuts`, options);
};

export const getGetShortcutsInEachMainPageQueryKey = (
  confStringIdx: string
) => {
  return [`/api/public/pco/${confStringIdx}/shortcuts`] as const;
};

export const getGetShortcutsInEachMainPageQueryOptions = <
  TData = Awaited<ReturnType<typeof getShortcutsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortcutsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetShortcutsInEachMainPageQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getShortcutsInEachMainPage>>
  > = ({ signal }) =>
    getShortcutsInEachMainPage(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getShortcutsInEachMainPage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetShortcutsInEachMainPageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getShortcutsInEachMainPage>>
>;
export type GetShortcutsInEachMainPageQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary public : getShortcutsInEachMainPage
 */
export const useGetShortcutsInEachMainPage = <
  TData = Awaited<ReturnType<typeof getShortcutsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortcutsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetShortcutsInEachMainPageQueryOptions(
    confStringIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 인사말 상세 페이지에 필요한 데이터 가져오기
 * @summary 인사말 : getPcoRegisterInfoImage
 */
export const getPcoRegisterInfoImage = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/register-info`, options);
};

export const getGetPcoRegisterInfoImageQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/register-info`] as const;
};

export const getGetPcoRegisterInfoImageQueryOptions = <
  TData = Awaited<ReturnType<typeof getPcoRegisterInfoImage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoRegisterInfoImage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPcoRegisterInfoImageQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPcoRegisterInfoImage>>
  > = ({ signal }) =>
    getPcoRegisterInfoImage(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPcoRegisterInfoImage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPcoRegisterInfoImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPcoRegisterInfoImage>>
>;
export type GetPcoRegisterInfoImageQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary 인사말 : getPcoRegisterInfoImage
 */
export const useGetPcoRegisterInfoImage = <
  TData = Awaited<ReturnType<typeof getPcoRegisterInfoImage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoRegisterInfoImage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetPcoRegisterInfoImageQueryOptions(
    confStringIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 후원사 목록 가져오기
 * @summary public : getSponsoredBy
 */
export const getMainSponsor = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SponsorVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/main-sponsor`, options);
};

export const getGetMainSponsorQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/main-sponsor`] as const;
};

export const getGetMainSponsorQueryOptions = <
  TData = Awaited<ReturnType<typeof getMainSponsor>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMainSponsor>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMainSponsorQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainSponsor>>> = ({
    signal,
  }) => getMainSponsor(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMainSponsor>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMainSponsorQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMainSponsor>>
>;
export type GetMainSponsorQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getSponsoredBy
 */
export const useGetMainSponsor = <
  TData = Awaited<ReturnType<typeof getMainSponsor>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMainSponsor>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMainSponsorQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 메인 장소 정보 가져오기
 * @summary public : getMainLocation
 */
export const getMainLocation = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoLocationVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/main-location`, options);
};

export const getGetMainLocationQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/main-location`] as const;
};

export const getGetMainLocationQueryOptions = <
  TData = Awaited<ReturnType<typeof getMainLocation>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMainLocation>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMainLocationQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainLocation>>> = ({
    signal,
  }) => getMainLocation(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMainLocation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMainLocationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMainLocation>>
>;
export type GetMainLocationQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getMainLocation
 */
export const useGetMainLocation = <
  TData = Awaited<ReturnType<typeof getMainLocation>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMainLocation>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMainLocationQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 메인 페이지 배너 정보 가져오기
 * @summary public : getMainBanner
 */
export const getMainBanner = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SponsorVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/main-banner`, options);
};

export const getGetMainBannerQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/main-banner`] as const;
};

export const getGetMainBannerQueryOptions = <
  TData = Awaited<ReturnType<typeof getMainBanner>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMainBanner>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMainBannerQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainBanner>>> = ({
    signal,
  }) => getMainBanner(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMainBanner>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMainBannerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMainBanner>>
>;
export type GetMainBannerQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getMainBanner
 */
export const useGetMainBanner = <
  TData = Awaited<ReturnType<typeof getMainBanner>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMainBanner>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMainBannerQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회 장소 상세 정보 가져오기
 * @summary location : checkAttendeeDisCountCode
 */
export const getPcoLocationInfo = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoLocationVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/location`, options);
};

export const getGetPcoLocationInfoQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/location`] as const;
};

export const getGetPcoLocationInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getPcoLocationInfo>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoLocationInfo>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPcoLocationInfoQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPcoLocationInfo>>
  > = ({ signal }) =>
    getPcoLocationInfo(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPcoLocationInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPcoLocationInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPcoLocationInfo>>
>;
export type GetPcoLocationInfoQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary location : checkAttendeeDisCountCode
 */
export const useGetPcoLocationInfo = <
  TData = Awaited<ReturnType<typeof getPcoLocationInfo>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoLocationInfo>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetPcoLocationInfoQueryOptions(
    confStringIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 인사말 상세 페이지에 필요한 데이터 가져오기
 * @summary 인사말 : getPcoGreetings
 */
export const getPcoGreetings = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/greetings`, options);
};

export const getGetPcoGreetingsQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/greetings`] as const;
};

export const getGetPcoGreetingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPcoGreetings>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoGreetings>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPcoGreetingsQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPcoGreetings>>> = ({
    signal,
  }) => getPcoGreetings(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPcoGreetings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPcoGreetingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPcoGreetings>>
>;
export type GetPcoGreetingsQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary 인사말 : getPcoGreetings
 */
export const useGetPcoGreetings = <
  TData = Awaited<ReturnType<typeof getPcoGreetings>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPcoGreetings>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetPcoGreetingsQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 카테고리별 프로그램 이미지 가져오기
 * @summary public : getCategoryProgramImage
 */
export const getCategoryProgramImage = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SessionCategoryVo>> => {
  return axios.get(
    `/api/public/pco/${confStringIdx}/full-program-image`,
    options
  );
};

export const getGetCategoryProgramImageQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/full-program-image`] as const;
};

export const getGetCategoryProgramImageQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategoryProgramImage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryProgramImage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCategoryProgramImageQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCategoryProgramImage>>
  > = ({ signal }) =>
    getCategoryProgramImage(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategoryProgramImage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCategoryProgramImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategoryProgramImage>>
>;
export type GetCategoryProgramImageQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getCategoryProgramImage
 */
export const useGetCategoryProgramImage = <
  TData = Awaited<ReturnType<typeof getCategoryProgramImage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryProgramImage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCategoryProgramImageQueryOptions(
    confStringIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 푸터에 워치하는 스푼서 목록 가져오기
 * @summary public : getSponsoredBy
 */
export const getFooterSponsor = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SponsorVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/footer-sponsor`, options);
};

export const getGetFooterSponsorQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/footer-sponsor`] as const;
};

export const getGetFooterSponsorQueryOptions = <
  TData = Awaited<ReturnType<typeof getFooterSponsor>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFooterSponsor>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFooterSponsorQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFooterSponsor>>
  > = ({ signal }) =>
    getFooterSponsor(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFooterSponsor>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFooterSponsorQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFooterSponsor>>
>;
export type GetFooterSponsorQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getSponsoredBy
 */
export const useGetFooterSponsor = <
  TData = Awaited<ReturnType<typeof getFooterSponsor>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFooterSponsor>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetFooterSponsorQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 연자 목록 가져오기
 * @summary public : getFaculty
 */
export const getFaculty = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<FacultyListResponse>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/faculty`, options);
};

export const getGetFacultyQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/faculty`] as const;
};

export const getGetFacultyQueryOptions = <
  TData = Awaited<ReturnType<typeof getFaculty>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFaculty>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFacultyQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFaculty>>> = ({
    signal,
  }) => getFaculty(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFaculty>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFacultyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFaculty>>
>;
export type GetFacultyQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getFaculty
 */
export const useGetFaculty = <
  TData = Awaited<ReturnType<typeof getFaculty>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFaculty>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetFacultyQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회 메인페이지 노출 메뉴들 가져오기
 * @summary public : getElementsInEachMainPage
 */
export const getElementsInEachMainPage = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/elements`, options);
};

export const getGetElementsInEachMainPageQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/elements`] as const;
};

export const getGetElementsInEachMainPageQueryOptions = <
  TData = Awaited<ReturnType<typeof getElementsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElementsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetElementsInEachMainPageQueryKey(confStringIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getElementsInEachMainPage>>
  > = ({ signal }) =>
    getElementsInEachMainPage(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getElementsInEachMainPage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetElementsInEachMainPageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getElementsInEachMainPage>>
>;
export type GetElementsInEachMainPageQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getElementsInEachMainPage
 */
export const useGetElementsInEachMainPage = <
  TData = Awaited<ReturnType<typeof getElementsInEachMainPage>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElementsInEachMainPage>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetElementsInEachMainPageQueryOptions(
    confStringIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 이사진 목록 가져오기
 * @summary public : getBoardMember
 */
export const getBoardMember = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoBoardMemberVo>> => {
  return axios.get(`/api/public/pco/${confStringIdx}/board-member`, options);
};

export const getGetBoardMemberQueryKey = (confStringIdx: string) => {
  return [`/api/public/pco/${confStringIdx}/board-member`] as const;
};

export const getGetBoardMemberQueryOptions = <
  TData = Awaited<ReturnType<typeof getBoardMember>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBoardMember>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBoardMemberQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBoardMember>>> = ({
    signal,
  }) => getBoardMember(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBoardMember>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBoardMemberQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBoardMember>>
>;
export type GetBoardMemberQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getBoardMember
 */
export const useGetBoardMember = <
  TData = Awaited<ReturnType<typeof getBoardMember>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBoardMember>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetBoardMemberQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 해당 학회의 연자 목록 가져오기
 * @summary public : getFaculty
 */
export const getPublicFacultyDetail = (
  facultyIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<FacultyListResponse>> => {
  return axios.get(`/api/public/pco/faculty/${facultyIdx}`, options);
};

export const getGetPublicFacultyDetailQueryKey = (facultyIdx: number) => {
  return [`/api/public/pco/faculty/${facultyIdx}`] as const;
};

export const getGetPublicFacultyDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getPublicFacultyDetail>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  facultyIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPublicFacultyDetail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPublicFacultyDetailQueryKey(facultyIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPublicFacultyDetail>>
  > = ({ signal }) =>
    getPublicFacultyDetail(facultyIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!facultyIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPublicFacultyDetail>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPublicFacultyDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPublicFacultyDetail>>
>;
export type GetPublicFacultyDetailQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary public : getFaculty
 */
export const useGetPublicFacultyDetail = <
  TData = Awaited<ReturnType<typeof getPublicFacultyDetail>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  facultyIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPublicFacultyDetail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetPublicFacultyDetailQueryOptions(
    facultyIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 현재 어드민 페이지가 열러 있는 모든 학회 목록 가져오기
 * @summary No Auth : getEnterprisePcoInAdminOpen
 */
export const getEnterprisePcoInAdminOpen = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> => {
  return axios.get(`/api/public/pco/admin-open`, options);
};

export const getGetEnterprisePcoInAdminOpenQueryKey = () => {
  return [`/api/public/pco/admin-open`] as const;
};

export const getGetEnterprisePcoInAdminOpenQueryOptions = <
  TData = Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>,
  TError = AxiosError<ResponseMessageVo>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetEnterprisePcoInAdminOpenQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>
  > = ({ signal }) => getEnterprisePcoInAdminOpen({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEnterprisePcoInAdminOpenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>
>;
export type GetEnterprisePcoInAdminOpenQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary No Auth : getEnterprisePcoInAdminOpen
 */
export const useGetEnterprisePcoInAdminOpen = <
  TData = Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>,
  TError = AxiosError<ResponseMessageVo>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEnterprisePcoInAdminOpen>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetEnterprisePcoInAdminOpenQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
