/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GetSurveys400, SurveyVo } from '../../model';

/**
 * 모든 설문조사 목록 가져오기
 * @summary getSurveys
 */
export const getSurveys = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SurveyVo>> => {
  return axios.get(`/api/medistaff/surveys`, options);
};

export const getGetSurveysQueryKey = () => {
  return [`/api/medistaff/surveys`] as const;
};

export const getGetSurveysQueryOptions = <
  TData = Awaited<ReturnType<typeof getSurveys>>,
  TError = AxiosError<GetSurveys400>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSurveys>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSurveysQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveys>>> = ({
    signal,
  }) => getSurveys({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSurveys>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSurveysQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSurveys>>
>;
export type GetSurveysQueryError = AxiosError<GetSurveys400>;

/**
 * @summary getSurveys
 */
export const useGetSurveys = <
  TData = Awaited<ReturnType<typeof getSurveys>>,
  TError = AxiosError<GetSurveys400>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSurveys>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSurveysQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
