/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type { AxiosError, AxiosRequestConfig } from 'axios';
import { EnterpriseListResVo } from '@/api/types/EnterpriseListResVo';
import { adminAxiosInstance } from '@/api/authApi';
import { TableSearchParams } from '@/api/types/TableSearchParams';
import { AxiosResponse } from 'axios/index';

interface ResponseMessageVo<T = any> {
  content?: T;
  enMessage?: string;
  error?: string;
  message?: string;
  status?: number;
}

/**
 * Enterprise Conference 목록 가져오기
 * @summary getEnterprisePcoList
 */
export const getEnterprisePcoList = (
  param: TableSearchParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EnterpriseListResVo>> => {
  return adminAxiosInstance
    .post(`/api/pco/top/enterprises`, param, options)
    .then((response) => {
      console.log('AxiosResponse response : ', response);
      return response.data.content;
    })
    .catch((error) => {
      console.log('AxiosResponse error: ', error);
      return null;
    });
};

export const getEnterprisePcoListQueryKey = () => {
  return [`/api/pco/top/enterprises`] as const;
};

export const getEnterprisePcoListQueryOptions = <
  TData = Awaited<ReturnType<typeof getEnterprisePcoList>>,
  TError = AxiosError<ResponseMessageVo>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEnterprisePcoList>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEnterprisePcoListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEnterprisePcoList>>
  > = ({ signal }) => getEnterprisePcoList({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEnterprisePcoList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEnterprisePcoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEnterprisePcoList>>
>;
export type GetEnterprisePcoListQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary getEnterprisePcoList
 */
export const useGetEnterprisePcoList = <
  TData = Awaited<ReturnType<typeof getEnterprisePcoList>>,
  TError = AxiosError<ResponseMessageVo>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEnterprisePcoList>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getEnterprisePcoListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

// 사용법 : const { data, isLoading, isError } = useGetEnterprisePcoList();
