/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GetSurveys1400, SurveyVo } from '../../model';

/**
 * 모든 설문조사 목록 가져오기 [Auth.MEDISTAFF_ADMIN_TOP만 허용]
 * @summary getSurveys
 */
export const getSurveys1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SurveyVo>> => {
  return axios.get(`/api/medistaff/admin/top/surveys`, options);
};

export const getGetSurveys1QueryKey = () => {
  return [`/api/medistaff/admin/top/surveys`] as const;
};

export const getGetSurveys1QueryOptions = <
  TData = Awaited<ReturnType<typeof getSurveys1>>,
  TError = AxiosError<GetSurveys1400>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSurveys1>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSurveys1QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveys1>>> = ({
    signal,
  }) => getSurveys1({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSurveys1>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSurveys1QueryResult = NonNullable<
  Awaited<ReturnType<typeof getSurveys1>>
>;
export type GetSurveys1QueryError = AxiosError<GetSurveys1400>;

/**
 * @summary getSurveys
 */
export const useGetSurveys1 = <
  TData = Awaited<ReturnType<typeof getSurveys1>>,
  TError = AxiosError<GetSurveys1400>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSurveys1>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSurveys1QueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
