/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AttendeePaymentFirstResponse,
  PaymentErrorVo,
  PaymentFinalRequest,
  PaymentFirstRequestGuest,
  RequestPaymentCancelTypeGuest200,
  RequestPaymentFail200,
  ResponseMessageVo,
} from '../../model';

/**
 * 비회원용 토스페이먼츠에서 결제를 요청하기 위한 필요한 정보 서버에서 가져오기
 * @summary all : getPcoInfoForFirst
 */
export const getPaymentInfoFromServerTypeGuest = (
  paymentFirstRequestGuest: PaymentFirstRequestGuest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentFirstResponse>> => {
  return axios.post(
    `/api/public/payment/first-request`,
    paymentFirstRequestGuest,
    options
  );
};

export const getGetPaymentInfoFromServerTypeGuestMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeGuest>>,
    TError,
    { data: PaymentFirstRequestGuest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getPaymentInfoFromServerTypeGuest>>,
  TError,
  { data: PaymentFirstRequestGuest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeGuest>>,
    { data: PaymentFirstRequestGuest }
  > = (props) => {
    const { data } = props ?? {};

    return getPaymentInfoFromServerTypeGuest(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetPaymentInfoFromServerTypeGuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof getPaymentInfoFromServerTypeGuest>>
>;
export type GetPaymentInfoFromServerTypeGuestMutationBody =
  PaymentFirstRequestGuest;
export type GetPaymentInfoFromServerTypeGuestMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary all : getPcoInfoForFirst
 */
export const useGetPaymentInfoFromServerTypeGuest = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeGuest>>,
    TError,
    { data: PaymentFirstRequestGuest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getGetPaymentInfoFromServerTypeGuestMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 토스페이먼츠 결제 성공 시 최종 결제 승인 요청을 보냅니다.
 * @summary 비회원전용 : getPcoInfoForFirst
 */
export const sendFinalPaymentApprovalRequestTypeQuest = (
  paymentFinalRequest: PaymentFinalRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentFirstResponse>> => {
  return axios.post(
    `/api/public/payment/final-payment-approval`,
    paymentFinalRequest,
    options
  );
};

export const getSendFinalPaymentApprovalRequestTypeQuestMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeQuest>>,
    TError,
    { data: PaymentFinalRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeQuest>>,
  TError,
  { data: PaymentFinalRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeQuest>>,
    { data: PaymentFinalRequest }
  > = (props) => {
    const { data } = props ?? {};

    return sendFinalPaymentApprovalRequestTypeQuest(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendFinalPaymentApprovalRequestTypeQuestMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeQuest>>
  >;
export type SendFinalPaymentApprovalRequestTypeQuestMutationBody =
  PaymentFinalRequest;
export type SendFinalPaymentApprovalRequestTypeQuestMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary 비회원전용 : getPcoInfoForFirst
 */
export const useSendFinalPaymentApprovalRequestTypeQuest = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeQuest>>,
    TError,
    { data: PaymentFinalRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getSendFinalPaymentApprovalRequestTypeQuestMutationOptions(options);

  return useMutation(mutationOptions);
};
export const requestPaymentFail = (
  paymentErrorVo: PaymentErrorVo,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<RequestPaymentFail200>> => {
  return axios.post(`/api/public/payment/fail`, paymentErrorVo, options);
};

export const getRequestPaymentFailMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestPaymentFail>>,
    TError,
    { data: PaymentErrorVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestPaymentFail>>,
  TError,
  { data: PaymentErrorVo },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestPaymentFail>>,
    { data: PaymentErrorVo }
  > = (props) => {
    const { data } = props ?? {};

    return requestPaymentFail(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestPaymentFailMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestPaymentFail>>
>;
export type RequestPaymentFailMutationBody = PaymentErrorVo;
export type RequestPaymentFailMutationError = AxiosError<unknown>;

export const useRequestPaymentFail = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestPaymentFail>>,
    TError,
    { data: PaymentErrorVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getRequestPaymentFailMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 토스페이먼츠 결제 성공 시 최종 결제 승인 요청을 보냅니다.
 * @summary Attendee 전용 : getPcoInfoForFirst
 */
export const sendFinalPaymentApprovalRequestTypeAttendee = (
  paymentFinalRequest: PaymentFinalRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentFirstResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/payment/final-payment-approval`,
    paymentFinalRequest,
    options
  );
};

export const getSendFinalPaymentApprovalRequestTypeAttendeeMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeAttendee>>,
    TError,
    { data: PaymentFinalRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeAttendee>>,
  TError,
  { data: PaymentFinalRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeAttendee>>,
    { data: PaymentFinalRequest }
  > = (props) => {
    const { data } = props ?? {};

    return sendFinalPaymentApprovalRequestTypeAttendee(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendFinalPaymentApprovalRequestTypeAttendeeMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeAttendee>>
  >;
export type SendFinalPaymentApprovalRequestTypeAttendeeMutationBody =
  PaymentFinalRequest;
export type SendFinalPaymentApprovalRequestTypeAttendeeMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary Attendee 전용 : getPcoInfoForFirst
 */
export const useSendFinalPaymentApprovalRequestTypeAttendee = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFinalPaymentApprovalRequestTypeAttendee>>,
    TError,
    { data: PaymentFinalRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getSendFinalPaymentApprovalRequestTypeAttendeeMutationOptions(options);

  return useMutation(mutationOptions);
};
export const requestPaymentCancelTypeGuest = (
  paymentKey: string,
  uuid: string,
  cancelReason: string,
  cancelAmount: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<RequestPaymentCancelTypeGuest200>> => {
  return axios.get(
    `/api/public/payment/cancel/${paymentKey}/${uuid}/${cancelReason}/${cancelAmount}`,
    options
  );
};

export const getRequestPaymentCancelTypeGuestQueryKey = (
  paymentKey: string,
  uuid: string,
  cancelReason: string,
  cancelAmount: string
) => {
  return [
    `/api/public/payment/cancel/${paymentKey}/${uuid}/${cancelReason}/${cancelAmount}`,
  ] as const;
};

export const getRequestPaymentCancelTypeGuestQueryOptions = <
  TData = Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>,
  TError = AxiosError<unknown>,
>(
  paymentKey: string,
  uuid: string,
  cancelReason: string,
  cancelAmount: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRequestPaymentCancelTypeGuestQueryKey(
      paymentKey,
      uuid,
      cancelReason,
      cancelAmount
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>
  > = ({ signal }) =>
    requestPaymentCancelTypeGuest(
      paymentKey,
      uuid,
      cancelReason,
      cancelAmount,
      { signal, ...axiosOptions }
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(paymentKey && uuid && cancelReason && cancelAmount),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RequestPaymentCancelTypeGuestQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>
>;
export type RequestPaymentCancelTypeGuestQueryError = AxiosError<unknown>;

export const useRequestPaymentCancelTypeGuest = <
  TData = Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>,
  TError = AxiosError<unknown>,
>(
  paymentKey: string,
  uuid: string,
  cancelReason: string,
  cancelAmount: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestPaymentCancelTypeGuest>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getRequestPaymentCancelTypeGuestQueryOptions(
    paymentKey,
    uuid,
    cancelReason,
    cancelAmount,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 결제 성공 페이지에서 해당 결제 내역 보여주기(본인만 가능)
 * @summary Attendee 본인만 : getPcoInfoForFirst
 */
export const getSuccessPaymentInfo = (
  wuserIdx: number,
  paymentKey: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentFirstResponse>> => {
  return axios.get(
    `/api/pco/client/attendee/${wuserIdx}/payment/success/${paymentKey}`,
    options
  );
};

export const getGetSuccessPaymentInfoQueryKey = (
  wuserIdx: number,
  paymentKey: string
) => {
  return [
    `/api/pco/client/attendee/${wuserIdx}/payment/success/${paymentKey}`,
  ] as const;
};

export const getGetSuccessPaymentInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getSuccessPaymentInfo>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  paymentKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSuccessPaymentInfo>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetSuccessPaymentInfoQueryKey(wuserIdx, paymentKey);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSuccessPaymentInfo>>
  > = ({ signal }) =>
    getSuccessPaymentInfo(wuserIdx, paymentKey, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(wuserIdx && paymentKey),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSuccessPaymentInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSuccessPaymentInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSuccessPaymentInfo>>
>;
export type GetSuccessPaymentInfoQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary Attendee 본인만 : getPcoInfoForFirst
 */
export const useGetSuccessPaymentInfo = <
  TData = Awaited<ReturnType<typeof getSuccessPaymentInfo>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  paymentKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSuccessPaymentInfo>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSuccessPaymentInfoQueryOptions(
    wuserIdx,
    paymentKey,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
