/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AllianceDtVo,
  EnterpriseDtVo,
  GetAlliancePcoDtBody,
  GetEnterprisePcoDTBody,
  ResponseMessageVo,
} from '../../model';

/**
 * Enterprise Conference 목록 가져오기
 * @summary getEnterprisePcoList
 */
export const getEnterprisePcoDT = (
  getEnterprisePcoDTBody: GetEnterprisePcoDTBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EnterpriseDtVo>> => {
  return axios.post(
    `/api/pco/top/enterprises`,
    getEnterprisePcoDTBody,
    options
  );
};

export const getGetEnterprisePcoDTMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    TError,
    { data: GetEnterprisePcoDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getEnterprisePcoDT>>,
  TError,
  { data: GetEnterprisePcoDTBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    { data: GetEnterprisePcoDTBody }
  > = (props) => {
    const { data } = props ?? {};

    return getEnterprisePcoDT(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetEnterprisePcoDTMutationResult = NonNullable<
  Awaited<ReturnType<typeof getEnterprisePcoDT>>
>;
export type GetEnterprisePcoDTMutationBody = GetEnterprisePcoDTBody;
export type GetEnterprisePcoDTMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary getEnterprisePcoList
 */
export const useGetEnterprisePcoDT = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    TError,
    { data: GetEnterprisePcoDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetEnterprisePcoDTMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Alliance Conference 목록 가져오기
 * @summary getAlliancePcoList
 */
export const getAlliancePcoDt = (
  getAlliancePcoDtBody: GetAlliancePcoDtBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AllianceDtVo>> => {
  return axios.post(`/api/pco/top/alliances`, getAlliancePcoDtBody, options);
};

export const getGetAlliancePcoDtMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    TError,
    { data: GetAlliancePcoDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAlliancePcoDt>>,
  TError,
  { data: GetAlliancePcoDtBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    { data: GetAlliancePcoDtBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAlliancePcoDt(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAlliancePcoDtMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAlliancePcoDt>>
>;
export type GetAlliancePcoDtMutationBody = GetAlliancePcoDtBody;
export type GetAlliancePcoDtMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary getAlliancePcoList
 */
export const useGetAlliancePcoDt = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    TError,
    { data: GetAlliancePcoDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAlliancePcoDtMutationOptions(options);

  return useMutation(mutationOptions);
};
