/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GetEnterprisePcoListBody, ResponseMessageVo } from '../../model';

/**
 * Enterprise Conference 목록 가져오기
 * @summary getEnterprisePcoList
 */
export const getEnterprisePcoList = (
  getEnterprisePcoListBody: GetEnterprisePcoListBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/pco/top/enterprises`,
    getEnterprisePcoListBody,
    options
  );
};

export const getGetEnterprisePcoListMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoList>>,
    TError,
    { data: GetEnterprisePcoListBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getEnterprisePcoList>>,
  TError,
  { data: GetEnterprisePcoListBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getEnterprisePcoList>>,
    { data: GetEnterprisePcoListBody }
  > = (props) => {
    const { data } = props ?? {};

    return getEnterprisePcoList(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetEnterprisePcoListMutationResult = NonNullable<
  Awaited<ReturnType<typeof getEnterprisePcoList>>
>;
export type GetEnterprisePcoListMutationBody = GetEnterprisePcoListBody;
export type GetEnterprisePcoListMutationError = AxiosError<unknown>;

/**
 * @summary getEnterprisePcoList
 */
export const useGetEnterprisePcoList = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoList>>,
    TError,
    { data: GetEnterprisePcoListBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetEnterprisePcoListMutationOptions(options);

  return useMutation(mutationOptions);
};
