/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AdditionalPaidProgramVo,
  AllianceDtVo,
  EnterpriseDtVo,
  GetAdditionalPaidProgramsParams,
  GetAlliancePcoDtBody,
  GetEnterprisePcoDTBody,
  GetOptionsParams,
  GetRegiFeeListParams,
  PcoDiscountVo,
  PcoRegiFeeVo,
  PcoRegisterOptionVo,
  ResponseMessageVo,
} from '../../model';

/**
 * Enterprise Conference 목록 가져오기
 * @summary Admin : getEnterprisePcoList
 */
export const getEnterprisePcoDT = (
  getEnterprisePcoDTBody: GetEnterprisePcoDTBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EnterpriseDtVo>> => {
  return axios.post(
    `/api/pco/medi-admin/enterprises`,
    getEnterprisePcoDTBody,
    options
  );
};

export const getGetEnterprisePcoDTMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    TError,
    { data: GetEnterprisePcoDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getEnterprisePcoDT>>,
  TError,
  { data: GetEnterprisePcoDTBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    { data: GetEnterprisePcoDTBody }
  > = (props) => {
    const { data } = props ?? {};

    return getEnterprisePcoDT(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetEnterprisePcoDTMutationResult = NonNullable<
  Awaited<ReturnType<typeof getEnterprisePcoDT>>
>;
export type GetEnterprisePcoDTMutationBody = GetEnterprisePcoDTBody;
export type GetEnterprisePcoDTMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary Admin : getEnterprisePcoList
 */
export const useGetEnterprisePcoDT = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnterprisePcoDT>>,
    TError,
    { data: GetEnterprisePcoDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetEnterprisePcoDTMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Alliance Conference 목록 가져오기
 * @summary Admin : getAlliancePcoList
 */
export const getAlliancePcoDt = (
  getAlliancePcoDtBody: GetAlliancePcoDtBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AllianceDtVo>> => {
  return axios.post(
    `/api/pco/medi-admin/alliances`,
    getAlliancePcoDtBody,
    options
  );
};

export const getGetAlliancePcoDtMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    TError,
    { data: GetAlliancePcoDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAlliancePcoDt>>,
  TError,
  { data: GetAlliancePcoDtBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    { data: GetAlliancePcoDtBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAlliancePcoDt(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAlliancePcoDtMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAlliancePcoDt>>
>;
export type GetAlliancePcoDtMutationBody = GetAlliancePcoDtBody;
export type GetAlliancePcoDtMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary Admin : getAlliancePcoList
 */
export const useGetAlliancePcoDt = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAlliancePcoDt>>,
    TError,
    { data: GetAlliancePcoDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAlliancePcoDtMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 해당 학회 사용자 할인 코드 확인
 * @summary after login : checkAttendeeDisCountCode
 */
export const checkAttendeeDisCountCode = (
  pcoDiscountVo: PcoDiscountVo,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoDiscountVo>> => {
  return axios.post(
    `/api/pco/client/attendee/check-discount-code`,
    pcoDiscountVo,
    options
  );
};

export const getCheckAttendeeDisCountCodeMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkAttendeeDisCountCode>>,
    TError,
    { data: PcoDiscountVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof checkAttendeeDisCountCode>>,
  TError,
  { data: PcoDiscountVo },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof checkAttendeeDisCountCode>>,
    { data: PcoDiscountVo }
  > = (props) => {
    const { data } = props ?? {};

    return checkAttendeeDisCountCode(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CheckAttendeeDisCountCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof checkAttendeeDisCountCode>>
>;
export type CheckAttendeeDisCountCodeMutationBody = PcoDiscountVo;
export type CheckAttendeeDisCountCodeMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary after login : checkAttendeeDisCountCode
 */
export const useCheckAttendeeDisCountCode = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkAttendeeDisCountCode>>,
    TError,
    { data: PcoDiscountVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getCheckAttendeeDisCountCodeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 사용자 등록시 추가로 필요한 옵션 정보 가져오기
 * @summary after login : getOptions
 */
export const getOptions = (
  params: GetOptionsParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoRegisterOptionVo>> => {
  return axios.get(`/api/pco/client/attendee/registration-option`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetOptionsQueryKey = (params: GetOptionsParams) => {
  return [
    `/api/pco/client/attendee/registration-option`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetOptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOptions>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOptions>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOptions>>> = ({
    signal,
  }) => getOptions(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOptions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOptions>>
>;
export type GetOptionsQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary after login : getOptions
 */
export const useGetOptions = <
  TData = Awaited<ReturnType<typeof getOptions>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOptions>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetOptionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 학회 등록비 목록 가져오기
 * @summary after login : getRegiFeeList
 */
export const getRegiFeeList = (
  params: GetRegiFeeListParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoRegiFeeVo>> => {
  return axios.get(`/api/pco/client/attendee/regi-fee`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetRegiFeeListQueryKey = (params: GetRegiFeeListParams) => {
  return [
    `/api/pco/client/attendee/regi-fee`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetRegiFeeListQueryOptions = <
  TData = Awaited<ReturnType<typeof getRegiFeeList>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetRegiFeeListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRegiFeeList>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRegiFeeListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegiFeeList>>> = ({
    signal,
  }) => getRegiFeeList(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRegiFeeList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRegiFeeListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRegiFeeList>>
>;
export type GetRegiFeeListQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary after login : getRegiFeeList
 */
export const useGetRegiFeeList = <
  TData = Awaited<ReturnType<typeof getRegiFeeList>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetRegiFeeListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRegiFeeList>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRegiFeeListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 학회 등록비 제외 추가 유료 프로그램 목록 가져오기
 * @summary after login : getAdditionalPaidProgram
 */
export const getAdditionalPaidPrograms = (
  params: GetAdditionalPaidProgramsParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AdditionalPaidProgramVo>> => {
  return axios.get(`/api/pco/client/attendee/additional-paid-program`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetAdditionalPaidProgramsQueryKey = (
  params: GetAdditionalPaidProgramsParams
) => {
  return [
    `/api/pco/client/attendee/additional-paid-program`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAdditionalPaidProgramsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdditionalPaidPrograms>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetAdditionalPaidProgramsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdditionalPaidPrograms>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdditionalPaidProgramsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdditionalPaidPrograms>>
  > = ({ signal }) =>
    getAdditionalPaidPrograms(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdditionalPaidPrograms>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdditionalPaidProgramsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdditionalPaidPrograms>>
>;
export type GetAdditionalPaidProgramsQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary after login : getAdditionalPaidProgram
 */
export const useGetAdditionalPaidPrograms = <
  TData = Awaited<ReturnType<typeof getAdditionalPaidPrograms>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  params: GetAdditionalPaidProgramsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdditionalPaidPrograms>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAdditionalPaidProgramsQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
