/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

/**
 * pco_admin : pco_admin_all_top
 * @summary admin_open_status가 active인 학회 리스트 가져오기
 */
export const getAdminOpenStatusActivePcoList = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.get(`/api/pco/medi-admin/admin-active-pco`, options);
};

export const getGetAdminOpenStatusActivePcoListQueryKey = () => {
  return [`/api/pco/medi-admin/admin-active-pco`] as const;
};

export const getGetAdminOpenStatusActivePcoListQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminOpenStatusActivePcoListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>
  > = ({ signal }) =>
    getAdminOpenStatusActivePcoList({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminOpenStatusActivePcoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>
>;
export type GetAdminOpenStatusActivePcoListQueryError = AxiosError<unknown>;

/**
 * @summary admin_open_status가 active인 학회 리스트 가져오기
 */
export const useGetAdminOpenStatusActivePcoList = <
  TData = Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAdminOpenStatusActivePcoList>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAdminOpenStatusActivePcoListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
