/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { InquiryEmailRequest, ResponseMessageVo } from '../../model';

/**
 * 문의하기 이메일 전송하기
 * @summary public : getCategoryProgramImage
 */
export const sendInquiryEmail = (
  inquiryEmailRequest: InquiryEmailRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/public/pco/email/inquiry`,
    inquiryEmailRequest,
    options
  );
};

export const getSendInquiryEmailMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendInquiryEmail>>,
    TError,
    { data: InquiryEmailRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendInquiryEmail>>,
  TError,
  { data: InquiryEmailRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendInquiryEmail>>,
    { data: InquiryEmailRequest }
  > = (props) => {
    const { data } = props ?? {};

    return sendInquiryEmail(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendInquiryEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendInquiryEmail>>
>;
export type SendInquiryEmailMutationBody = InquiryEmailRequest;
export type SendInquiryEmailMutationError = AxiosError<unknown>;

/**
 * @summary public : getCategoryProgramImage
 */
export const useSendInquiryEmail = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendInquiryEmail>>,
    TError,
    { data: InquiryEmailRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getSendInquiryEmailMutationOptions(options);

  return useMutation(mutationOptions);
};
