/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 학회 & 사무국
 */
export interface AppExposureConferenceDT {
  conferenceIdx: number;
  conferenceName: string;
  committeeName: string;
  conferencePreRegiStartT: string;
  conferenceDate: string;
  onlineOfflineSupportStatus: 'online_offline' | 'online_only' | 'offline_only';
  conferenceApplyStatus: 'active' | 'apply' | 'delete';
}

export interface AppExposureConferenceDetailResponse {
  conferencePreRegiStartT: string;
  conferenceIdx?: number; // 학회 일련번호
  conferenceName: string; // 학회명
  committeeName: string; // 주최/주관
  electiveCredit?: number; // 일반 평점
  essentialCredit?: number; // 필수 평점
  conferenceDate?: string; // 학회 일시
  conferencePreDate?: string; // 사전등록 일시
  conferenceRegistrationT: string; // 등록일시

  conferenceDesc?: string; // 내용
  homeUrl?: string; // 홈페이지 URL
  preUrl?: string; // 사전등록 URL

  name?: string; // 담당자 성함
  phone?: string; // 담당자 전화번호
  email?: string; // 이메일

  resultAlertEmail?: string; // 결과 안내받을 이메일
  posterUrl?: string; // 이미지

  locationInfo?: string; // 장소
  onlineOfflineSupportStatus: 'online_offline' | 'online_only' | 'offline_only';
  conferenceApplyStatus: 'active' | 'apply' | 'delete';
  locationName?: string; // (hidden) 장소명
  locationAddr?: string; // (hidden) 장소 주소
  locationAddrDetail?: string; // (hidden) 장소 상세 주소
  userLevel?: string; // 참여 권한 DB
  userLevelInfo?: string; // 참여 권한 가공
  specialtyNameList?: string[]; // 대상 전문 과목 목록
  languageType?: string; // (hidden) 언어 타입, 기본값 "ko"
}
