/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 토스 페이먼츠로 실제 결제하기전 서버에서 필요한 정보들을 취합하여 프론트엔드에 전달
 */
export interface AttendeePaymentFirstResponse {
  amount?: number;
  clientKey?: string;
  customerEmail?: string;
  customerName?: string;
  orderId?: string;
  orderName?: string;
}
