/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import type { AttendeePcoRegisterRequestAdditionalPaidProgramItem } from './attendeePcoRegisterRequestAdditionalPaidProgramItem';
import type { AttendeePcoRegisterRequestOptionsItem } from './attendeePcoRegisterRequestOptionsItem';

/**
 * 사용자가 학회 등록을 하기 위한 Request Vo
 */
export interface AttendeePcoRegisterRequest {
  additionalPaidProgram?: AttendeePcoRegisterRequestAdditionalPaidProgramItem[];
  amount?: number;
  attendeeIdx: number;
  conferenceIdx: number;
  discountIdx?: number;
  indicatedAmount?: number;
  isPreRegistration: number;
  options?: AttendeePcoRegisterRequestOptionsItem[];
  optionsJson: string;
  orderId: string;
  regifeeIdx: number;
  sessionCategoryIdxList?: number[];
}
