/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CommitteeVo } from './committeeVo';
import type { AttendeeReceiptVo } from './attendeeReceiptVo';
import type { PcoFileVo } from './pcoFileVo';
import type { AttendeePaymentReceiptResponseRefundPolicyHashMapItem } from './attendeePaymentReceiptResponseRefundPolicyHashMapItem';

/**
 * 참여자 영수증 응답
 */
export interface AttendeePaymentReceiptResponse {
  committee?: CommitteeVo;
  conferenceName?: string;
  conferenceStartT?: string;
  receipt?: AttendeeReceiptVo;
  receiptFiles?: PcoFileVo[];
  refundPolicyHashMap?: AttendeePaymentReceiptResponseRefundPolicyHashMapItem[];
}
