/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import type { AttendeePaymentFirstRequestAdditionalPaidProgramItem } from './attendeePaymentFirstRequestAdditionalPaidProgramItem';

/**
 * 서버에서 데이터를 취합하기 위한 결제 요청에 필요한 정보
 */
export interface AttendeePaymentFirstRequest {
  additionalPaidProgram?: AttendeePaymentFirstRequestAdditionalPaidProgramItem[];
  amount: number;
  attendeeIdx: number;
  attendeePaymentType: string;
  indicatedAmount?: number;
  orderId: string;
  orderName?: string;
  regifeeIdx?: number;
  sessionCategoryIdxList?: number[];
}
