/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

export interface FacultyVo {
  auth?: string;
  conferenceIdx?: number;
  conferenceUserContactNumber?: string;
  conferenceUserCreateT?: string;
  conferenceUserEmail?: string;
  conferenceUserIdx?: number;
  conferenceUserName?: string;
  conferenceUserPwd?: string;
  facultyAffiliation?: string;
  facultyCreateT?: string;
  facultyFile?: Blob;
  facultyIdx?: number;
  facultyLastAccessTime?: string;
  facultyPayStatus?: string;
  facultyProfileHost?: string;
  facultyProfileName?: string;
  facultyProfilePath?: string;
  facultyProgramIdx?: number;
  facultyProgramRole?: string;
  facultyTempPwd?: string;
  facultyType?: string;
  programPay?: string;
  sessionCategoryIdx?: number;
  sessionGroupIdx?: number;
  sessionIdx?: number;
  totalCount?: number;
  uniqueName?: string;
  userIdx?: number;
}
