/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

export interface PcoAttendeeIdentityVerificationRequest {
  authenticationReason: string;
  birthDate: string;
  conferenceIdx: number;
  encodedPhone?: string;
  gender: string;
  name: string;
  ntvFrnrCd: string;
  phone: string;
  registrationType?: string;
  serviceType?: string;
  smsResendYn: string;
  telComCd: string;
  txSeqNo?: string;
}
