/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * tbl_conference_regifee : 학회 등록비 옵션
 */
export interface PcoRegiFeeVo {
  conferenceIdx?: number;
  isPreRegistration?: number;
  limitCount?: number;
  regifeeIdx?: number;
  regifeeName?: string;
  regifeePrice?: number;
  selectedCount?: number;
  status?: string;
}
