/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 각각의 학회에서 보여줄 Html setting 정보
 */
export interface TermsVo {
  conferenceIdx?: number;
  content?: string;
  contentEn?: string;
  createTime?: string;
  description?: string;
  exposureLocation?: string;
  exposureOrder?: string;
  isAvailable?: string;
  isRequired?: string;
  termsIdx?: number;
  title?: string;
  titleEn?: string;
  type?: string;
  version?: string;
}
