import type { ColorScheme } from '@/styles/theme/types';

export const navColorStyles = {
  dark: {
    '--SideNav-background': 'var(--mui-palette-neutral-800)',
    '--SideNav-color': 'var(--mui-palette-common-white)',
    '--SideNav-border': 'none',
    '--NavGroup-title-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-color': 'var(--mui-palette-neutral-300)',
    '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
    '--NavItem-active-background': 'var(--mui-palette-primary-main)',
    '--NavItem-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
    '--NavItem-icon-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-icon-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
    '--NavItem-expand-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-children-border': 'var(--mui-palette-neutral-700)',
    '--NavItem-children-indicator': 'var(--mui-palette-neutral-400)',
    '--Workspaces-background': 'var(--mui-palette-neutral-950)',
    '--Workspaces-border-color': 'var(--mui-palette-neutral-700)',
    '--Workspaces-title-color': 'var(--mui-palette-neutral-400)',
    '--Workspaces-name-color': 'var(--mui-palette-neutral-300)',
    '--Workspaces-expand-color': 'var(--mui-palette-neutral-400)',
  },
  light: {
    '--SideNav-background': 'var(--mui-palette-neutral-950)',
    '--SideNav-color': 'var(--mui-palette-common-white)',
    '--SideNav-border': 'none',
    '--NavGroup-title-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-color': 'var(--mui-palette-neutral-300)',
    '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
    '--NavItem-active-background': 'var(--mui-palette-primary-main)',
    '--NavItem-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
    '--NavItem-icon-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-icon-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
    '--NavItem-expand-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-children-border': 'var(--mui-palette-neutral-700)',
    '--NavItem-children-indicator': 'var(--mui-palette-neutral-400)',
    '--Workspaces-background': 'var(--mui-palette-neutral-950)',
    '--Workspaces-border-color': 'var(--mui-palette-neutral-700)',
    '--Workspaces-title-color': 'var(--mui-palette-neutral-400)',
    '--Workspaces-name-color': 'var(--mui-palette-neutral-300)',
    '--Workspaces-expand-color': 'var(--mui-palette-neutral-400)',
  },
} satisfies Record<ColorScheme, Record<string, string>>;
