/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  GetJoinAttendeeDtBody,
  JoinAttendeeDtVo,
  ResponseMessageVo,
} from '../../model';

/**
 * @summary admin-*: 가입 회원 리스트
 */
export const getJoinAttendeeDt = (
  getJoinAttendeeDtBody: GetJoinAttendeeDtBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<JoinAttendeeDtVo>> => {
  return axios.post(
    `/api/pco/admin/join-attendee-dt`,
    getJoinAttendeeDtBody,
    options
  );
};

export const getGetJoinAttendeeDtMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getJoinAttendeeDt>>,
    TError,
    { data: GetJoinAttendeeDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getJoinAttendeeDt>>,
  TError,
  { data: GetJoinAttendeeDtBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getJoinAttendeeDt>>,
    { data: GetJoinAttendeeDtBody }
  > = (props) => {
    const { data } = props ?? {};

    return getJoinAttendeeDt(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetJoinAttendeeDtMutationResult = NonNullable<
  Awaited<ReturnType<typeof getJoinAttendeeDt>>
>;
export type GetJoinAttendeeDtMutationBody = GetJoinAttendeeDtBody;
export type GetJoinAttendeeDtMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary admin-*: 가입 회원 리스트
 */
export const useGetJoinAttendeeDt = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getJoinAttendeeDt>>,
    TError,
    { data: GetJoinAttendeeDtBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetJoinAttendeeDtMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary admin-*-top : 수동 계좌이체 환불 완료 상태로 변경후 환불 완료 이메일 보내기
 */
export const updateTransferRefundStatusAndNotifyByEmail = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(`/api/pco/admin/each/top/`, undefined, options);
};

export const getUpdateTransferRefundStatusAndNotifyByEmailMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTransferRefundStatusAndNotifyByEmail>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTransferRefundStatusAndNotifyByEmail>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTransferRefundStatusAndNotifyByEmail>>,
    void
  > = () => {
    return updateTransferRefundStatusAndNotifyByEmail(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTransferRefundStatusAndNotifyByEmailMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof updateTransferRefundStatusAndNotifyByEmail>>
  >;

export type UpdateTransferRefundStatusAndNotifyByEmailMutationError =
  AxiosError<unknown>;

/**
 * @summary admin-*-top : 수동 계좌이체 환불 완료 상태로 변경후 환불 완료 이메일 보내기
 */
export const useUpdateTransferRefundStatusAndNotifyByEmail = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTransferRefundStatusAndNotifyByEmail>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getUpdateTransferRefundStatusAndNotifyByEmailMutationOptions(options);

  return useMutation(mutationOptions);
};
