/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  AttendeePaymentFirstRequest,
  AttendeePaymentFirstResponse,
  AttendeePaymentReceiptResponse,
  AttendeePaymentVo,
  AttendeePcoRegisterCancel200,
  AttendeePcoRegisterCancelBody,
  AttendeePcoRegisterRequest,
  ChangeTempToNormalMemberBody,
  CheckEmailDuplicate200,
  GetAttendeeBasicPlanBody,
  GetAttendeePaymentHistoryBody,
  GetAttendeePaymentInfoBody,
  GetAttendeePcoRegisterInfoBody,
  ManualPaymentRefundRequest,
  PasswordChangeReqVo,
  PaymentCancelRequest,
  PcoAttendeeMyPageRequest,
  PcoAttendeeMyPageResponse,
  PcoAttendeeSignUpRequest,
  PcoRegisterResponse,
  ResponseMessageVo,
  SendPaymentSuccessEmail200,
  SendPaymentSuccessEmailParams,
} from '../../model';

/**
 * 학회 사용자 회원가입
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const attendeeSignUp = (
  pcoAttendeeSignUpRequest: PcoAttendeeSignUpRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/public/pco/client-attendee-register`,
    pcoAttendeeSignUpRequest,
    options
  );
};

export const getAttendeeSignUpMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeeSignUp>>,
    TError,
    { data: PcoAttendeeSignUpRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof attendeeSignUp>>,
  TError,
  { data: PcoAttendeeSignUpRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof attendeeSignUp>>,
    { data: PcoAttendeeSignUpRequest }
  > = (props) => {
    const { data } = props ?? {};

    return attendeeSignUp(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AttendeeSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof attendeeSignUp>>
>;
export type AttendeeSignUpMutationBody = PcoAttendeeSignUpRequest;
export type AttendeeSignUpMutationError = AxiosError<unknown>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useAttendeeSignUp = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeeSignUp>>,
    TError,
    { data: PcoAttendeeSignUpRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getAttendeeSignUpMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 기회원인 멤버 정규회원으로 변환
 * @summary public :
 */
export const changeTempToNormalMember = (
  changeTempToNormalMemberBody: ChangeTempToNormalMemberBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/public/pco/change-temp-to-normal-member`,
    changeTempToNormalMemberBody,
    options
  );
};

export const getChangeTempToNormalMemberMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeTempToNormalMember>>,
    TError,
    { data: ChangeTempToNormalMemberBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeTempToNormalMember>>,
  TError,
  { data: ChangeTempToNormalMemberBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeTempToNormalMember>>,
    { data: ChangeTempToNormalMemberBody }
  > = (props) => {
    const { data } = props ?? {};

    return changeTempToNormalMember(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeTempToNormalMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof changeTempToNormalMember>>
>;
export type ChangeTempToNormalMemberMutationBody = ChangeTempToNormalMemberBody;
export type ChangeTempToNormalMemberMutationError = AxiosError<unknown>;

/**
 * @summary public :
 */
export const useChangeTempToNormalMember = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeTempToNormalMember>>,
    TError,
    { data: ChangeTempToNormalMemberBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getChangeTempToNormalMemberMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 학회 사용자 마이페이지 정보 가져오기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const getAttendeeMyPageInfoByWUserIdx = (
  wuserIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoAttendeeMyPageResponse>> => {
  return axios.get(`/api/pco/client/attendee/${wuserIdx}`, options);
};

export const getGetAttendeeMyPageInfoByWUserIdxQueryKey = (
  wuserIdx: number
) => {
  return [`/api/pco/client/attendee/${wuserIdx}`] as const;
};

export const getGetAttendeeMyPageInfoByWUserIdxQueryOptions = <
  TData = Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAttendeeMyPageInfoByWUserIdxQueryKey(wuserIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>
  > = ({ signal }) =>
    getAttendeeMyPageInfoByWUserIdx(wuserIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!wuserIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAttendeeMyPageInfoByWUserIdxQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>
>;
export type GetAttendeeMyPageInfoByWUserIdxQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useGetAttendeeMyPageInfoByWUserIdx = <
  TData = Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttendeeMyPageInfoByWUserIdx>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAttendeeMyPageInfoByWUserIdxQueryOptions(
    wuserIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 학회 사용자 마이페이지 데이터 업데이트 하기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const updateAttendeeMyPageData = (
  wuserIdx: number,
  pcoAttendeeMyPageRequest: PcoAttendeeMyPageRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ResponseMessageVo>> => {
  return axios.post(
    `/api/pco/client/attendee/${wuserIdx}`,
    pcoAttendeeMyPageRequest,
    options
  );
};

export const getUpdateAttendeeMyPageDataMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAttendeeMyPageData>>,
    TError,
    { wuserIdx: number; data: PcoAttendeeMyPageRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAttendeeMyPageData>>,
  TError,
  { wuserIdx: number; data: PcoAttendeeMyPageRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAttendeeMyPageData>>,
    { wuserIdx: number; data: PcoAttendeeMyPageRequest }
  > = (props) => {
    const { wuserIdx, data } = props ?? {};

    return updateAttendeeMyPageData(wuserIdx, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAttendeeMyPageDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAttendeeMyPageData>>
>;
export type UpdateAttendeeMyPageDataMutationBody = PcoAttendeeMyPageRequest;
export type UpdateAttendeeMyPageDataMutationError = AxiosError<unknown>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useUpdateAttendeeMyPageData = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAttendeeMyPageData>>,
    TError,
    { wuserIdx: number; data: PcoAttendeeMyPageRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getUpdateAttendeeMyPageDataMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 사용자 학회 정보 등록하기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const attendeePcoRegister = (
  attendeePcoRegisterRequest: AttendeePcoRegisterRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoAttendeeMyPageResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/pco-register`,
    attendeePcoRegisterRequest,
    options
  );
};

export const getAttendeePcoRegisterMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeePcoRegister>>,
    TError,
    { data: AttendeePcoRegisterRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof attendeePcoRegister>>,
  TError,
  { data: AttendeePcoRegisterRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof attendeePcoRegister>>,
    { data: AttendeePcoRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return attendeePcoRegister(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AttendeePcoRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof attendeePcoRegister>>
>;
export type AttendeePcoRegisterMutationBody = AttendeePcoRegisterRequest;
export type AttendeePcoRegisterMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useAttendeePcoRegister = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeePcoRegister>>,
    TError,
    { data: AttendeePcoRegisterRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getAttendeePcoRegisterMutationOptions(options);

  return useMutation(mutationOptions);
};
export const attendeePcoRegisterCancel = (
  attendeePcoRegisterCancelBody: AttendeePcoRegisterCancelBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePcoRegisterCancel200>> => {
  return axios.post(
    `/api/pco/client/attendee/pco-register/cancel`,
    attendeePcoRegisterCancelBody,
    options
  );
};

export const getAttendeePcoRegisterCancelMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeePcoRegisterCancel>>,
    TError,
    { data: AttendeePcoRegisterCancelBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof attendeePcoRegisterCancel>>,
  TError,
  { data: AttendeePcoRegisterCancelBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof attendeePcoRegisterCancel>>,
    { data: AttendeePcoRegisterCancelBody }
  > = (props) => {
    const { data } = props ?? {};

    return attendeePcoRegisterCancel(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AttendeePcoRegisterCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof attendeePcoRegisterCancel>>
>;
export type AttendeePcoRegisterCancelMutationBody =
  AttendeePcoRegisterCancelBody;
export type AttendeePcoRegisterCancelMutationError = AxiosError<unknown>;

export const useAttendeePcoRegisterCancel = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeePcoRegisterCancel>>,
    TError,
    { data: AttendeePcoRegisterCancelBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getAttendeePcoRegisterCancelMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Attendee 학회 정보 가져 오기
 * @summary pco_each_client_attendee : 본인만 가능
 */
export const getAttendeePcoRegisterInfo = (
  getAttendeePcoRegisterInfoBody: GetAttendeePcoRegisterInfoBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoRegisterResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/pco-register-info`,
    getAttendeePcoRegisterInfoBody,
    options
  );
};

export const getGetAttendeePcoRegisterInfoMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePcoRegisterInfo>>,
    TError,
    { data: GetAttendeePcoRegisterInfoBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAttendeePcoRegisterInfo>>,
  TError,
  { data: GetAttendeePcoRegisterInfoBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAttendeePcoRegisterInfo>>,
    { data: GetAttendeePcoRegisterInfoBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAttendeePcoRegisterInfo(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAttendeePcoRegisterInfoMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAttendeePcoRegisterInfo>>
>;
export type GetAttendeePcoRegisterInfoMutationBody =
  GetAttendeePcoRegisterInfoBody;
export type GetAttendeePcoRegisterInfoMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : 본인만 가능
 */
export const useGetAttendeePcoRegisterInfo = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePcoRegisterInfo>>,
    TError,
    { data: GetAttendeePcoRegisterInfoBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAttendeePcoRegisterInfoMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 토스페이먼츠에서 결제를 요청하기 위한 필요한 정보 서버에서 가져오기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const getPaymentInfoFromServerTypeAttendee = (
  attendeePaymentFirstRequest: AttendeePaymentFirstRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentFirstResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/payment`,
    attendeePaymentFirstRequest,
    options
  );
};

export const getGetPaymentInfoFromServerTypeAttendeeMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeAttendee>>,
    TError,
    { data: AttendeePaymentFirstRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getPaymentInfoFromServerTypeAttendee>>,
  TError,
  { data: AttendeePaymentFirstRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeAttendee>>,
    { data: AttendeePaymentFirstRequest }
  > = (props) => {
    const { data } = props ?? {};

    return getPaymentInfoFromServerTypeAttendee(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetPaymentInfoFromServerTypeAttendeeMutationResult = NonNullable<
  Awaited<ReturnType<typeof getPaymentInfoFromServerTypeAttendee>>
>;
export type GetPaymentInfoFromServerTypeAttendeeMutationBody =
  AttendeePaymentFirstRequest;
export type GetPaymentInfoFromServerTypeAttendeeMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useGetPaymentInfoFromServerTypeAttendee = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfoFromServerTypeAttendee>>,
    TError,
    { data: AttendeePaymentFirstRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getGetPaymentInfoFromServerTypeAttendeeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 마이페이지 -> 내 영수증 보기에서 필요한 데이터들 가져오기
 * @summary attendee 본인만
 */
export const getAttendeePaymentInfo = (
  getAttendeePaymentInfoBody: GetAttendeePaymentInfoBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentReceiptResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/payment/receipt`,
    getAttendeePaymentInfoBody,
    options
  );
};

export const getGetAttendeePaymentInfoMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePaymentInfo>>,
    TError,
    { data: GetAttendeePaymentInfoBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAttendeePaymentInfo>>,
  TError,
  { data: GetAttendeePaymentInfoBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAttendeePaymentInfo>>,
    { data: GetAttendeePaymentInfoBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAttendeePaymentInfo(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAttendeePaymentInfoMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAttendeePaymentInfo>>
>;
export type GetAttendeePaymentInfoMutationBody = GetAttendeePaymentInfoBody;
export type GetAttendeePaymentInfoMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary attendee 본인만
 */
export const useGetAttendeePaymentInfo = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePaymentInfo>>,
    TError,
    { data: GetAttendeePaymentInfoBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAttendeePaymentInfoMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 마이페이지 -> 사용자 결제 여부 가져오기
 * @summary attendee 본인만
 */
export const getAttendeePaymentHistory = (
  getAttendeePaymentHistoryBody: GetAttendeePaymentHistoryBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentVo[]>> => {
  return axios.post(
    `/api/pco/client/attendee/payment/history`,
    getAttendeePaymentHistoryBody,
    options
  );
};

export const getGetAttendeePaymentHistoryMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePaymentHistory>>,
    TError,
    { data: GetAttendeePaymentHistoryBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAttendeePaymentHistory>>,
  TError,
  { data: GetAttendeePaymentHistoryBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAttendeePaymentHistory>>,
    { data: GetAttendeePaymentHistoryBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAttendeePaymentHistory(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAttendeePaymentHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAttendeePaymentHistory>>
>;
export type GetAttendeePaymentHistoryMutationBody =
  GetAttendeePaymentHistoryBody;
export type GetAttendeePaymentHistoryMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary attendee 본인만
 */
export const useGetAttendeePaymentHistory = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeePaymentHistory>>,
    TError,
    { data: GetAttendeePaymentHistoryBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAttendeePaymentHistoryMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 마이페이지 -> 결제 취소
 * @summary attendee 본인만
 */
export const cancelAttendeePayment = (
  paymentCancelRequest: PaymentCancelRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PaymentCancelRequest>> => {
  return axios.post(
    `/api/pco/client/attendee/payment/cancel`,
    paymentCancelRequest,
    options
  );
};

export const getCancelAttendeePaymentMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelAttendeePayment>>,
    TError,
    { data: PaymentCancelRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelAttendeePayment>>,
  TError,
  { data: PaymentCancelRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelAttendeePayment>>,
    { data: PaymentCancelRequest }
  > = (props) => {
    const { data } = props ?? {};

    return cancelAttendeePayment(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelAttendeePaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelAttendeePayment>>
>;
export type CancelAttendeePaymentMutationBody = PaymentCancelRequest;
export type CancelAttendeePaymentMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary attendee 본인만
 */
export const useCancelAttendeePayment = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelAttendeePayment>>,
    TError,
    { data: PaymentCancelRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getCancelAttendeePaymentMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 사용자 결제에 필요한 정보 가져오기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const getPaymentInfo = (
  attendeePaymentFirstRequest: AttendeePaymentFirstRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoAttendeeMyPageResponse>> => {
  return axios.post(
    `/api/pco/client/attendee/payment-info`,
    attendeePaymentFirstRequest,
    options
  );
};

export const getGetPaymentInfoMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfo>>,
    TError,
    { data: AttendeePaymentFirstRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getPaymentInfo>>,
  TError,
  { data: AttendeePaymentFirstRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getPaymentInfo>>,
    { data: AttendeePaymentFirstRequest }
  > = (props) => {
    const { data } = props ?? {};

    return getPaymentInfo(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetPaymentInfoMutationResult = NonNullable<
  Awaited<ReturnType<typeof getPaymentInfo>>
>;
export type GetPaymentInfoMutationBody = AttendeePaymentFirstRequest;
export type GetPaymentInfoMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useGetPaymentInfo = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPaymentInfo>>,
    TError,
    { data: AttendeePaymentFirstRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetPaymentInfoMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 마이페이지 -> 사용자 결제 여부 가져오기
 * @summary attendee 본인만
 */
export const attendeeManualPaymentRefund = (
  manualPaymentRefundRequest: ManualPaymentRefundRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AttendeePaymentVo[]>> => {
  return axios.post(
    `/api/pco/client/attendee/manual-payment/refund`,
    manualPaymentRefundRequest,
    options
  );
};

export const getAttendeeManualPaymentRefundMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeeManualPaymentRefund>>,
    TError,
    { data: ManualPaymentRefundRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof attendeeManualPaymentRefund>>,
  TError,
  { data: ManualPaymentRefundRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof attendeeManualPaymentRefund>>,
    { data: ManualPaymentRefundRequest }
  > = (props) => {
    const { data } = props ?? {};

    return attendeeManualPaymentRefund(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AttendeeManualPaymentRefundMutationResult = NonNullable<
  Awaited<ReturnType<typeof attendeeManualPaymentRefund>>
>;
export type AttendeeManualPaymentRefundMutationBody =
  ManualPaymentRefundRequest;
export type AttendeeManualPaymentRefundMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary attendee 본인만
 */
export const useAttendeeManualPaymentRefund = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendeeManualPaymentRefund>>,
    TError,
    { data: ManualPaymentRefundRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getAttendeeManualPaymentRefundMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 비밀번호 변경
 * @summary pco attendee|faculty : pcoClientChangePassword
 */
export const pcoClientChangePassword = (
  passwordChangeReqVo: PasswordChangeReqVo,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PasswordChangeReqVo>> => {
  return axios.post(
    `/api/pco/client/attendee/change-password`,
    passwordChangeReqVo,
    options
  );
};

export const getPcoClientChangePasswordMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pcoClientChangePassword>>,
    TError,
    { data: PasswordChangeReqVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pcoClientChangePassword>>,
  TError,
  { data: PasswordChangeReqVo },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pcoClientChangePassword>>,
    { data: PasswordChangeReqVo }
  > = (props) => {
    const { data } = props ?? {};

    return pcoClientChangePassword(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PcoClientChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof pcoClientChangePassword>>
>;
export type PcoClientChangePasswordMutationBody = PasswordChangeReqVo;
export type PcoClientChangePasswordMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco attendee|faculty : pcoClientChangePassword
 */
export const usePcoClientChangePassword = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pcoClientChangePassword>>,
    TError,
    { data: PasswordChangeReqVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getPcoClientChangePasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 마이페이지 -> 사용자 등록 여부 가져오기
 * @summary attendee 본인만
 */
export const getAttendeeBasicPlan = (
  getAttendeeBasicPlanBody: GetAttendeeBasicPlanBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<number>> => {
  return axios.post(
    `/api/pco/client/attendee/basic-plan`,
    getAttendeeBasicPlanBody,
    options
  );
};

export const getGetAttendeeBasicPlanMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeeBasicPlan>>,
    TError,
    { data: GetAttendeeBasicPlanBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAttendeeBasicPlan>>,
  TError,
  { data: GetAttendeeBasicPlanBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAttendeeBasicPlan>>,
    { data: GetAttendeeBasicPlanBody }
  > = (props) => {
    const { data } = props ?? {};

    return getAttendeeBasicPlan(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAttendeeBasicPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAttendeeBasicPlan>>
>;
export type GetAttendeeBasicPlanMutationBody = GetAttendeeBasicPlanBody;
export type GetAttendeeBasicPlanMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary attendee 본인만
 */
export const useGetAttendeeBasicPlan = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAttendeeBasicPlan>>,
    TError,
    { data: GetAttendeeBasicPlanBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetAttendeeBasicPlanMutationOptions(options);

  return useMutation(mutationOptions);
};
export const checkEmailDuplicate = (
  confStringIdx: string,
  email: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<CheckEmailDuplicate200>> => {
  return axios.get(
    `/api/public/pco/${confStringIdx}/user/email-check/${email}`,
    options
  );
};

export const getCheckEmailDuplicateQueryKey = (
  confStringIdx: string,
  email: string
) => {
  return [
    `/api/public/pco/${confStringIdx}/user/email-check/${email}`,
  ] as const;
};

export const getCheckEmailDuplicateQueryOptions = <
  TData = Awaited<ReturnType<typeof checkEmailDuplicate>>,
  TError = AxiosError<unknown>,
>(
  confStringIdx: string,
  email: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkEmailDuplicate>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCheckEmailDuplicateQueryKey(confStringIdx, email);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof checkEmailDuplicate>>
  > = ({ signal }) =>
    checkEmailDuplicate(confStringIdx, email, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(confStringIdx && email),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof checkEmailDuplicate>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CheckEmailDuplicateQueryResult = NonNullable<
  Awaited<ReturnType<typeof checkEmailDuplicate>>
>;
export type CheckEmailDuplicateQueryError = AxiosError<unknown>;

export const useCheckEmailDuplicate = <
  TData = Awaited<ReturnType<typeof checkEmailDuplicate>>,
  TError = AxiosError<unknown>,
>(
  confStringIdx: string,
  email: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkEmailDuplicate>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCheckEmailDuplicateQueryOptions(
    confStringIdx,
    email,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 사용자 학회 정보 등록했던 내용 취소하기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const requestPaymentCancelByAdmin = (
  wuserIdx: number,
  paymentRequestIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PcoAttendeeMyPageResponse>> => {
  return axios.get(
    `/api/pco/client/attendee/${wuserIdx}/payment-cancel/${paymentRequestIdx}`,
    options
  );
};

export const getRequestPaymentCancelByAdminQueryKey = (
  wuserIdx: number,
  paymentRequestIdx: number
) => {
  return [
    `/api/pco/client/attendee/${wuserIdx}/payment-cancel/${paymentRequestIdx}`,
  ] as const;
};

export const getRequestPaymentCancelByAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  paymentRequestIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRequestPaymentCancelByAdminQueryKey(wuserIdx, paymentRequestIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>
  > = ({ signal }) =>
    requestPaymentCancelByAdmin(wuserIdx, paymentRequestIdx, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(wuserIdx && paymentRequestIdx),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RequestPaymentCancelByAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>
>;
export type RequestPaymentCancelByAdminQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useRequestPaymentCancelByAdmin = <
  TData = Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  paymentRequestIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestPaymentCancelByAdmin>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getRequestPaymentCancelByAdminQueryOptions(
    wuserIdx,
    paymentRequestIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const sendPaymentSuccessEmail = (
  params: SendPaymentSuccessEmailParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SendPaymentSuccessEmail200>> => {
  return axios.get(`/api/pco/client/attendee/payment/success/email`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getSendPaymentSuccessEmailQueryKey = (
  params: SendPaymentSuccessEmailParams
) => {
  return [
    `/api/pco/client/attendee/payment/success/email`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSendPaymentSuccessEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof sendPaymentSuccessEmail>>,
  TError = AxiosError<unknown>,
>(
  params: SendPaymentSuccessEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sendPaymentSuccessEmail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSendPaymentSuccessEmailQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sendPaymentSuccessEmail>>
  > = ({ signal }) =>
    sendPaymentSuccessEmail(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sendPaymentSuccessEmail>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SendPaymentSuccessEmailQueryResult = NonNullable<
  Awaited<ReturnType<typeof sendPaymentSuccessEmail>>
>;
export type SendPaymentSuccessEmailQueryError = AxiosError<unknown>;

export const useSendPaymentSuccessEmail = <
  TData = Awaited<ReturnType<typeof sendPaymentSuccessEmail>>,
  TError = AxiosError<unknown>,
>(
  params: SendPaymentSuccessEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof sendPaymentSuccessEmail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSendPaymentSuccessEmailQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 로그인 후 추가 정보 가져오기
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const requestAdditionalApiAfterLogin = (
  wuserIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.get(
    `/api/pco/client/attendee/login-success/${wuserIdx}`,
    options
  );
};

export const getRequestAdditionalApiAfterLoginQueryKey = (wuserIdx: number) => {
  return [`/api/pco/client/attendee/login-success/${wuserIdx}`] as const;
};

export const getRequestAdditionalApiAfterLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRequestAdditionalApiAfterLoginQueryKey(wuserIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>
  > = ({ signal }) =>
    requestAdditionalApiAfterLogin(wuserIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!wuserIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RequestAdditionalApiAfterLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>
>;
export type RequestAdditionalApiAfterLoginQueryError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary pco_each_client_attendee : getPcoInfoForFirst
 */
export const useRequestAdditionalApiAfterLogin = <
  TData = Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  wuserIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof requestAdditionalApiAfterLogin>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getRequestAdditionalApiAfterLoginQueryOptions(
    wuserIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
