/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  GetProgramDTBody,
  GetSessionGroupDetail200,
  ProgramDtVo,
  ResponseMessageVo,
  UpdateProgramCategoryBody,
  UpdateProgramSessionGroupBody,
  UpdateProgramSessionGroupDetail200,
  UpdateProgramSessionGroupDetailBody,
} from '../../model';

/**
 * 프로그램 리스트 가져오기
 * @summary PCO-ADMIN : getProgramDT
 */
export const getProgramDT = (
  confStringIdx: string,
  getProgramDTBody: GetProgramDTBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ProgramDtVo[]>> => {
  return axios.post(
    `/api/pco/each-admin/${confStringIdx}/program-dt`,
    getProgramDTBody,
    options
  );
};

export const getGetProgramDTMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getProgramDT>>,
    TError,
    { confStringIdx: string; data: GetProgramDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getProgramDT>>,
  TError,
  { confStringIdx: string; data: GetProgramDTBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getProgramDT>>,
    { confStringIdx: string; data: GetProgramDTBody }
  > = (props) => {
    const { confStringIdx, data } = props ?? {};

    return getProgramDT(confStringIdx, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetProgramDTMutationResult = NonNullable<
  Awaited<ReturnType<typeof getProgramDT>>
>;
export type GetProgramDTMutationBody = GetProgramDTBody;
export type GetProgramDTMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary PCO-ADMIN : getProgramDT
 */
export const useGetProgramDT = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getProgramDT>>,
    TError,
    { confStringIdx: string; data: GetProgramDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetProgramDTMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 프로그램 세션 그룹 등록 및 수정
 * @summary PCO-ADMIN : updateProgramCategory
 */
export const updateProgramSessionGroup = (
  updateProgramSessionGroupBody: UpdateProgramSessionGroupBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> => {
  return axios.post(
    `/api/pco/each-admin/top/program/session-group`,
    updateProgramSessionGroupBody,
    options
  );
};

export const getUpdateProgramSessionGroupMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramSessionGroup>>,
    TError,
    { data: UpdateProgramSessionGroupBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProgramSessionGroup>>,
  TError,
  { data: UpdateProgramSessionGroupBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProgramSessionGroup>>,
    { data: UpdateProgramSessionGroupBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateProgramSessionGroup(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProgramSessionGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProgramSessionGroup>>
>;
export type UpdateProgramSessionGroupMutationBody =
  UpdateProgramSessionGroupBody;
export type UpdateProgramSessionGroupMutationError =
  AxiosError<ResponseMessageVo>;

/**
 * @summary PCO-ADMIN : updateProgramCategory
 */
export const useUpdateProgramSessionGroup = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramSessionGroup>>,
    TError,
    { data: UpdateProgramSessionGroupBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getUpdateProgramSessionGroupMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 관리자 : 세션 그룹 디테일 페이지 정보 입력 & 수정하기
 * @summary PCO-ADMIN : updateProgramSessionGroupDetail
 */
export const updateProgramSessionGroupDetail = (
  updateProgramSessionGroupDetailBody: UpdateProgramSessionGroupDetailBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<UpdateProgramSessionGroupDetail200>> => {
  return axios.post(
    `/api/pco/each-admin/top/program/session-group-detail`,
    updateProgramSessionGroupDetailBody,
    options
  );
};

export const getUpdateProgramSessionGroupDetailMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramSessionGroupDetail>>,
    TError,
    { data: UpdateProgramSessionGroupDetailBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProgramSessionGroupDetail>>,
  TError,
  { data: UpdateProgramSessionGroupDetailBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProgramSessionGroupDetail>>,
    { data: UpdateProgramSessionGroupDetailBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateProgramSessionGroupDetail(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProgramSessionGroupDetailMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProgramSessionGroupDetail>>
>;
export type UpdateProgramSessionGroupDetailMutationBody =
  UpdateProgramSessionGroupDetailBody;
export type UpdateProgramSessionGroupDetailMutationError = AxiosError<unknown>;

/**
 * @summary PCO-ADMIN : updateProgramSessionGroupDetail
 */
export const useUpdateProgramSessionGroupDetail = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramSessionGroupDetail>>,
    TError,
    { data: UpdateProgramSessionGroupDetailBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getUpdateProgramSessionGroupDetailMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 프로그램 카테고리 등록하기
 * @summary PCO-ADMIN : updateProgramCategory
 */
export const updateProgramCategory = (
  updateProgramCategoryBody: UpdateProgramCategoryBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> => {
  return axios.post(
    `/api/pco/each-admin/top/program/category`,
    updateProgramCategoryBody,
    options
  );
};

export const getUpdateProgramCategoryMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramCategory>>,
    TError,
    { data: UpdateProgramCategoryBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProgramCategory>>,
  TError,
  { data: UpdateProgramCategoryBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProgramCategory>>,
    { data: UpdateProgramCategoryBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateProgramCategory(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProgramCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProgramCategory>>
>;
export type UpdateProgramCategoryMutationBody = UpdateProgramCategoryBody;
export type UpdateProgramCategoryMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary PCO-ADMIN : updateProgramCategory
 */
export const useUpdateProgramCategory = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgramCategory>>,
    TError,
    { data: UpdateProgramCategoryBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getUpdateProgramCategoryMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 해당 학회의 프로그램 정보 가져오기(세션 제외)
 * @summary PCO-ADMIN : getProgram
 */
export const getProgram = (
  confStringIdx: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> => {
  return axios.get(`/api/pco/each-admin/${confStringIdx}/programs`, options);
};

export const getGetProgramQueryKey = (confStringIdx: string) => {
  return [`/api/pco/each-admin/${confStringIdx}/programs`] as const;
};

export const getGetProgramQueryOptions = <
  TData = Awaited<ReturnType<typeof getProgram>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgram>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProgramQueryKey(confStringIdx);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgram>>> = ({
    signal,
  }) => getProgram(confStringIdx, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!confStringIdx,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProgram>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProgramQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProgram>>
>;
export type GetProgramQueryError = AxiosError<ResponseMessageVo>;

/**
 * @summary PCO-ADMIN : getProgram
 */
export const useGetProgram = <
  TData = Awaited<ReturnType<typeof getProgram>>,
  TError = AxiosError<ResponseMessageVo>,
>(
  confStringIdx: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgram>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProgramQueryOptions(confStringIdx, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 관리자 : 세션 그룹 디테일 페이지 정보 가져오기
 * @summary PCO-ADMIN : getSessionGroupDetail
 */
export const getSessionGroupDetail = (
  confStringIdx: string,
  sessionGroupIdx: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<GetSessionGroupDetail200>> => {
  return axios.get(
    `/api/pco/each-admin/${confStringIdx}/program/session-group/${sessionGroupIdx}`,
    options
  );
};

export const getGetSessionGroupDetailQueryKey = (
  confStringIdx: string,
  sessionGroupIdx: number
) => {
  return [
    `/api/pco/each-admin/${confStringIdx}/program/session-group/${sessionGroupIdx}`,
  ] as const;
};

export const getGetSessionGroupDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionGroupDetail>>,
  TError = AxiosError<unknown>,
>(
  confStringIdx: string,
  sessionGroupIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionGroupDetail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetSessionGroupDetailQueryKey(confStringIdx, sessionGroupIdx);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSessionGroupDetail>>
  > = ({ signal }) =>
    getSessionGroupDetail(confStringIdx, sessionGroupIdx, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(confStringIdx && sessionGroupIdx),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionGroupDetail>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSessionGroupDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSessionGroupDetail>>
>;
export type GetSessionGroupDetailQueryError = AxiosError<unknown>;

/**
 * @summary PCO-ADMIN : getSessionGroupDetail
 */
export const useGetSessionGroupDetail = <
  TData = Awaited<ReturnType<typeof getSessionGroupDetail>>,
  TError = AxiosError<unknown>,
>(
  confStringIdx: string,
  sessionGroupIdx: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSessionGroupDetail>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSessionGroupDetailQueryOptions(
    confStringIdx,
    sessionGroupIdx,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
