/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  GetProgramDTBody,
  ProgramDtVo,
  ResponseMessageVo,
} from '../../model';

/**
 * 학회 프로그램 정보 가져오기
 * @summary getProgramDT
 */
export const getProgramDT = (
  getProgramDTBody: GetProgramDTBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ProgramDtVo[]>> => {
  return axios.post(`/api/pco/programs`, getProgramDTBody, options);
};

export const getGetProgramDTMutationOptions = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getProgramDT>>,
    TError,
    { data: GetProgramDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getProgramDT>>,
  TError,
  { data: GetProgramDTBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getProgramDT>>,
    { data: GetProgramDTBody }
  > = (props) => {
    const { data } = props ?? {};

    return getProgramDT(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetProgramDTMutationResult = NonNullable<
  Awaited<ReturnType<typeof getProgramDT>>
>;
export type GetProgramDTMutationBody = GetProgramDTBody;
export type GetProgramDTMutationError = AxiosError<ResponseMessageVo>;

/**
 * @summary getProgramDT
 */
export const useGetProgramDT = <
  TError = AxiosError<ResponseMessageVo>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getProgramDT>>,
    TError,
    { data: GetProgramDTBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getGetProgramDTMutationOptions(options);

  return useMutation(mutationOptions);
};
