/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  TestFailReturnMap200,
  TestSuccessReturnMap200,
  TestSuccessReturnVo200,
} from '../../model';

/**
 * 성공시 Vo를 반환
 * @summary 성공시 Vo를 반환
 */
export const testSuccessReturnVo = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TestSuccessReturnVo200>> => {
  return axios.get(`/api/test/success/vo`, options);
};

export const getTestSuccessReturnVoQueryKey = () => {
  return [`/api/test/success/vo`] as const;
};

export const getTestSuccessReturnVoQueryOptions = <
  TData = Awaited<ReturnType<typeof testSuccessReturnVo>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnVo>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTestSuccessReturnVoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof testSuccessReturnVo>>
  > = ({ signal }) => testSuccessReturnVo({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnVo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TestSuccessReturnVoQueryResult = NonNullable<
  Awaited<ReturnType<typeof testSuccessReturnVo>>
>;
export type TestSuccessReturnVoQueryError = AxiosError<unknown>;

/**
 * @summary 성공시 Vo를 반환
 */
export const useTestSuccessReturnVo = <
  TData = Awaited<ReturnType<typeof testSuccessReturnVo>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnVo>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTestSuccessReturnVoQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 성공시 Map을 반환
 * @summary 성공시 Map을 반환
 */
export const testSuccessReturnMap = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TestSuccessReturnMap200>> => {
  return axios.get(`/api/test/success/map`, options);
};

export const getTestSuccessReturnMapQueryKey = () => {
  return [`/api/test/success/map`] as const;
};

export const getTestSuccessReturnMapQueryOptions = <
  TData = Awaited<ReturnType<typeof testSuccessReturnMap>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnMap>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTestSuccessReturnMapQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof testSuccessReturnMap>>
  > = ({ signal }) => testSuccessReturnMap({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnMap>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TestSuccessReturnMapQueryResult = NonNullable<
  Awaited<ReturnType<typeof testSuccessReturnMap>>
>;
export type TestSuccessReturnMapQueryError = AxiosError<unknown>;

/**
 * @summary 성공시 Map을 반환
 */
export const useTestSuccessReturnMap = <
  TData = Awaited<ReturnType<typeof testSuccessReturnMap>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testSuccessReturnMap>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTestSuccessReturnMapQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 실패시 Map을 반환
 * @summary 실패시 Map을 반환
 */
export const testFailReturnMap = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TestFailReturnMap200>> => {
  return axios.get(`/api/test/fail/map`, options);
};

export const getTestFailReturnMapQueryKey = () => {
  return [`/api/test/fail/map`] as const;
};

export const getTestFailReturnMapQueryOptions = <
  TData = Awaited<ReturnType<typeof testFailReturnMap>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testFailReturnMap>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTestFailReturnMapQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof testFailReturnMap>>
  > = ({ signal }) => testFailReturnMap({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof testFailReturnMap>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TestFailReturnMapQueryResult = NonNullable<
  Awaited<ReturnType<typeof testFailReturnMap>>
>;
export type TestFailReturnMapQueryError = AxiosError<unknown>;

/**
 * @summary 실패시 Map을 반환
 */
export const useTestFailReturnMap = <
  TData = Awaited<ReturnType<typeof testFailReturnMap>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof testFailReturnMap>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTestFailReturnMapQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
