/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * 메디스태프 어드민 API & 학회 어드민 API 서버 구성하기
 * 로그인을 제외한 메디스태프 어드민의 모든 API와 학회 관련 API를 구성합니다.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  IdentityVerificationRequestOne200,
  IdentityVerificationRequestTwo200,
  PcoAttendeeIdentityVerificationRequest,
  PcoAttendeeRequestTwoVo,
} from '../../model';

export const identityVerificationRequestTwo = (
  pcoAttendeeRequestTwoVo: PcoAttendeeRequestTwoVo,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<IdentityVerificationRequestTwo200>> => {
  return axios.post(
    `/api/public/pco/identity-verification-two`,
    pcoAttendeeRequestTwoVo,
    options
  );
};

export const getIdentityVerificationRequestTwoMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityVerificationRequestTwo>>,
    TError,
    { data: PcoAttendeeRequestTwoVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityVerificationRequestTwo>>,
  TError,
  { data: PcoAttendeeRequestTwoVo },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityVerificationRequestTwo>>,
    { data: PcoAttendeeRequestTwoVo }
  > = (props) => {
    const { data } = props ?? {};

    return identityVerificationRequestTwo(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityVerificationRequestTwoMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityVerificationRequestTwo>>
>;
export type IdentityVerificationRequestTwoMutationBody =
  PcoAttendeeRequestTwoVo;
export type IdentityVerificationRequestTwoMutationError = AxiosError<unknown>;

export const useIdentityVerificationRequestTwo = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityVerificationRequestTwo>>,
    TError,
    { data: PcoAttendeeRequestTwoVo },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getIdentityVerificationRequestTwoMutationOptions(options);

  return useMutation(mutationOptions);
};
export const identityVerificationRequestOne = (
  pcoAttendeeIdentityVerificationRequest: PcoAttendeeIdentityVerificationRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<IdentityVerificationRequestOne200>> => {
  return axios.post(
    `/api/public/pco/identity-verification-one`,
    pcoAttendeeIdentityVerificationRequest,
    options
  );
};

export const getIdentityVerificationRequestOneMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityVerificationRequestOne>>,
    TError,
    { data: PcoAttendeeIdentityVerificationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityVerificationRequestOne>>,
  TError,
  { data: PcoAttendeeIdentityVerificationRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityVerificationRequestOne>>,
    { data: PcoAttendeeIdentityVerificationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityVerificationRequestOne(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityVerificationRequestOneMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityVerificationRequestOne>>
>;
export type IdentityVerificationRequestOneMutationBody =
  PcoAttendeeIdentityVerificationRequest;
export type IdentityVerificationRequestOneMutationError = AxiosError<unknown>;

export const useIdentityVerificationRequestOne = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityVerificationRequestOne>>,
    TError,
    { data: PcoAttendeeIdentityVerificationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions =
    getIdentityVerificationRequestOneMutationOptions(options);

  return useMutation(mutationOptions);
};
